name: Simple CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install numpy matplotlib
        
    - name: Test basic imports
      run: |
        cd src
        python -c "
        from config import Params
        from model import create_model
        print('✅ Basic imports successful')
        
        config = Params(batch_size=32, epochs=1)
        model = create_model('simple', hidden_nodes=16)
        print('✅ Basic functionality test passed')
        " 